### PR TITLE
fixed crashes when two machines are attested at the same time

### LINKED ISSUE #340: planetmint-god crashed when two machine were supposed to be attested at the same time
During Jürgen's Trust Anchor presentation, he and I simultaneously attested our trust anchor. That made the application crash and thus no liquid assets were issued:

- [x] 1. we should fix the bug
- [ ] 2. we should come up with a plan if something like that happens in production: can we somehow kick off the liquid asset notarization manually for the two attested machines now? 

Logs: 
```
...
Mar 06 11:00:50 ip-10-21-27-161 planetmint-god[27029]: 11:00AM INF [app] Issuing Machine NFT: name:"plmnt1z4najnpgxntjljm548ff7fky35dactvsk9ma7n" issuerPlanetmint:"pmpb7uMKHjAiJRDCqfig7KchKg5VwhsoyXzajgnX9N8bxg1
cPXKJVHMBQNdJCuYknnNrWm8792t81ydoRuPUSEgarxpKdBignPfrCgU1m36EpzG" issuerLiquid:"xpub6FaAYKn5Ao1J84DPPEWNDP8XVvzwLiTxGthCM18JU4zesDomSX5QBtQBUQJcyBHyfLpKKVnNXHnGxFJcnN131NTSjwC9nvf5iv1ewk15M7T" machineId:"02F40ED
3B20975D0677123521FD4BE44E960B6879FDC979ED62336BE11CD1AF474" metadata:<gps:"{\"Country\":\"AT\",\"Region\":\"3\",\"City\":\"vienna\",\"CityLatLong\":\"48.208174,16.373819\"}" device:"{\"Category\":\"RDDLTasmota\
", \"Manufacturer\":\"R&C\"}" assetDefinition:"{\"Version\":\"0.2\"}" > type:1 machineIdSignature:"E00C34D286480E9D8BCB311409870A2078FC04959570AEEF7D1AA6A7154A37042114911A1BE81910FE9CF32C07DC4DFB66BC2277DE5A8D98
AB48746BFC5C1A23" address:"plmnt1z4najnpgxntjljm548ff7fky35dactvsk9ma7n"  module=server
Mar 06 11:00:50 ip-10-21-27-161 planetmint-god[27029]: 11:00AM INF [app] Issuing Machine NFT: name:"plmnt139nyz9739qyg05xqp0n0j8c25z0jt9lfnr8na4" issuerPlanetmint:"pmpb7vCmMPHpUdgkxmBhEBfZsYUJFe6vuprY8UNoG2sTb2r8qhBs9Y3fMTQcpen22VcLLpkmceNBtFscnKyqMBuJPvWMpsfEYoX9RuTrq9S2kua" issuerLiquid:"xpub6GRcbyuBM1UrEmEBoQxukgBhCjiPYwJd9EYgT9dTZQvEJfv5CPmoNimuge7EXZ7GVTtpMiQuXT6HKRGpS3oHoGHWY97pmWFGSm1Qz7krgLE" machineId:"028CF25192B4501350C01BF2D62B7CBFFD2ACF58FC211441F63C393B390CEAA415" metadata:<gps:"{\"Country\":\"AT\",\"Region\":\"9\",\"City\":\"vienna\",\"CityLatLong\":\"48.208174,16.373819\"}" device:"{\"Category\":\"RDDLTasmotaJS\", \"Manufacturer\":\"R&C\"}" assetDefinition:"{\"Version\":\"0.2\"}" > type:1 machineIdSignature:"CDE95672E1BE3033F94B2EA751CED46236F57CF2B1799A00DE44BA8107CB65C40F4716ADAAEDA3AC2B5F7B222E0A81C01A3490258547C161EC8F9AA80E9FA3F5" address:"plmnt139nyz9739qyg05xqp0n0j8c25z0jt9lfnr8na4"  module=server
Mar 06 11:00:50 ip-10-21-27-161 planetmint-god[27029]: 11:00AM INF executed block height=687032 module=state num_invalid_txs=0 num_valid_txs=2
Mar 06 11:00:50 ip-10-21-27-161 planetmint-god[27029]: 11:00AM INF commit synced commit=436F6D6D697449447B5B34372032343520313020323334203135322031313820313830203131352037382032312036312032313320373420373020313034203135372033352031333120313934203739203433203234362031313720323032203320323120323533203135372032343720313133203132392039355D3A41374242387D module=server
Mar 06 11:00:50 ip-10-21-27-161 planetmint-god[27029]: 11:00AM INF committed state app_hash=2FF50AEA9876B4734E153DD54A46689D2383C24F2BF675CA0315FD9DF771815F height=687032 module=state num_txs=2
Mar 06 11:00:51 ip-10-21-27-161 planetmint-god[27029]: 11:00AM INF indexed block exents height=687032 module=txindex
Mar 06 11:00:52 ip-10-21-27-161 planetmint-god[27029]: 11:00AM INF [app] Liquid Token Issuance assetID: db6b9d5ac03d8cf6cd993f5cdc215d42bbfade71e639d6d69ead689566a81f9c contract: {"entity":{"domain":"testnet-assets.rddl.io"},"issuer_pubkey":"0328a57a1b9afbc2fb3c15d7d2088fae440d01fc75129b66a926d5bae4a297f2bc","machine_addr":"plmnt139nyz9739qyg05xqp0n0j8c25z0jt9lfnr8na4","name":"plmnt139nyz9739qyg05xqp0n0j8c25z0jt9lfnr8na4","precision":0,"version":0} tx: 407f25cbeb0f55798d933f97b6ebdd778e6044fb63380378911c8bc790956d4d module=server
Mar 06 11:00:52 ip-10-21-27-161 planetmint-god[27029]: 2024/03/06 11:00:52 not accepted by mempool
Mar 06 11:00:52 ip-10-21-27-161 systemd[1]: planetmint-go.service: Main process exited, code=exited, status=1/FAILURE
Mar 06 11:00:52 ip-10-21-27-161 systemd[1]: planetmint-go.service: Failed with result 'exit-code'.
Mar 06 11:00:52 ip-10-21-27-161 systemd[1]: planetmint-go.service: Consumed 1h 29min 126ms CPU time.
Mar 06 11:00:52 ip-10-21-27-161 systemd[1]: planetmint-go.service: Scheduled restart job, restart counter is at 1.
Mar 06 11:00:52 ip-10-21-27-161 systemd[1]: Stopped Planetmint.
```

### PR DESCRIPTION
**Pull request by eckelj**
* added creation of random machines to prepare a test case
* setting all the consensus timeout values at once (if changed)
* mutex protection of the elements tx crafting methods (sequential processing)
* Extending the TestMachineNFTIssuance test case to parallel threads and threading issues
* moving all elements-rpc usage to the elementd-connector.go file
* removed accidental panic/fatal call

closes #340

### CODE REVIEW

File: util/machine_nft_test.go [hunk 1]
```diff
@@ -44,14 +47,25 @@ func TestRegisterNFT(t *testing.T) {
...
-	assert.NoError(t, err)
+	for i := 0; i < 10; i++ {
+		wg.Add(1)
+		go func() {
+			randomInt := rand.Int()
+			sk, pk := sample.KeyPair(randomInt)
+			machine := moduleobject.MachineRandom(pk, pk, sk, "address "+strconv.Itoa(randomInt), randomInt)
+			goCtx := sdk.WrapSDKContext(ctx)
+
+			err := util.IssueMachineNFT(goCtx, &machine, "https", "testnet-assets.rddl.io", "register_asset")
```
Comment (jmastr) [inline util/machine_nft_test.go:65]: please don't switch from variables back to hard-coding:
```
err := util.IssueMachineNFT(goCtx, &machine, params.AssetRegistryScheme, params.AssetRegistryDomain, params.AssetRegistryPath)
```

File: testutil/moduleobject/sampleobject.go [hunk 2]
```diff
@@ -66,6 +67,39 @@ func Machine(name, pubKey string, prvKey string, address string) machinetypes.Ma
...
+	signatureHex := hex.EncodeToString(sign)
+
+	if address == "" {
+		address = sample.Secp256k1AccAddress().String()
+	}
+
+	m := machinetypes.Machine{
+		Name:               name + strconv.Itoa(random),
+		Ticker:             name + strconv.Itoa(random) + "_ticker",
+		Domain:             "lab.r3c.network",
```
Comment (jmastr) [inline testutil/moduleobject/sampleobject.go:88]: Not crucial but let's switch here to `testnet-assets.rddl.io`

**Review by jmastr — CHANGES_REQUESTED** [review]

**Review by jmastr — APPROVED** [review]
